# Analytics info
google_analytics_id: UA-411531-10

# For Atom Feed
domain: thegeekfest.com
author: THE Geek Fest Team
email: geekfest@cpcc.edu
title: THE Geek Fest

# Event Information
event_date: "Thursday, November 9th, 2017"
event_time: "9am - 3pm"
event_location: "CPCC's Levine Campus"
social-media:
  - "facebook": "https://www.facebook.com/thegeekfest"
  - "twitter": "https://twitter.com/thegeekfest"
  - "github-alt": "https://github.com/thegeekfest/thegeekfest.github.io"
  - "google-plus": "https://plus.google.com/u/0/+centralpiedmontcommunitycollege/"
interest_form: "http://snapsurvey.cpcc.edu/snapwebhost/s.asp?k=151031992390

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: []

# Handling Reading
safe:         false
include:      [".htaccess", "assets", "participate", "thanks"]
exclude:      ["*.sublime-project", "Gemfile", "Gemfile.lock", "params.json", "README.md", "temp", "Vagrantfile"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: nil
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4001
host:    0.0.0.0
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      nil

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

  coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               style

redcloth:
  hard_breaks: true
